### PR TITLE
Bump to guice 4.2.2

### PR DESCRIPTION
**Pull request by nicolasblaye**
For some reason, I couldn't resolve scala-guice because of guice 4.2.0. By bumping the version to 4.2.2, everything seems fine

### CODE REVIEW

**Comment by nbauernfeind** [comment]
Seems fine to me. @tsuckow If you do a release, you should consider making one for the latest RC of 2.13 too.

**Comment by 0xRoch** [comment]
👍

**Comment by tsuckow** [comment]
I might get this done Saturday. Keep nagging me if I don't, I need to setup
a new box for development

**Comment by tsuckow** [comment]
4.2.2 away 🚢

Edit: Sorry it took a month

**Pull request merged**
