### PR TITLE
update library dependencies, sbt version, and scala versions

### PR DESCRIPTION
**Pull request by dvic**
- guice 4.1.0
- scalatest 2.2.6
- jsr305 3.0.1
- sbt 0.13.12
- scala 2.11.8 and 2.10.6

### CODE REVIEW

**Comment by tsuckow** [comment]
Should update the Travis config file too

**Comment by tsuckow** [comment]
Should also bump the version of this library to 4.1.0-SNAPSHOT

**Comment by dvic** [comment]
I have rewritten now everything into two commits. Let me know if it needs anything else.

I see that you have a development branch, please note that I pushed this to my master branch (I'm not sure with which branch you want to merge it).

**Comment by tsuckow** [comment]
That master branch has been more of a pain than a benefit. So I cherry picked to develop and axed the master branch completely. I'll see about making a snapshot test release hopefully sometime this weekend.

**Comment by tsuckow** [comment]
I deployed a 4.1.0-SNAPSHOT which also includes Scala 2.12.0-M5 If you could give it a spin and see if it works for what you are doing that would be great. If there is no negative feedback I'll publish it proper.

**Comment by dvic** [comment]
Looks good to me.

**Comment by tsuckow** [comment]
Released 4.1.0, thanks for the PR

**Pull request closed without merging**
